name: 'clang-format lint'
author: 'Slobodan Kletnikov (DoozyX)'
description: 'Github Action that check if code is formatted correctly using clang-format'
branding:
  icon: 'align-left'
  color: 'green'
inputs:
  source:
    description: 'Source folder to check formatting'
    required: false
    default: '.'
  exclude:
    description: 'Folder(s) to exclude from formatting check'
    required: false
    default: 'none'
  extensions:
    description: 'List of extensions to check'
    required: false
    default: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
runs:
  using: 'docker'
  image: 'docker://gnuradio/clang-format-lint:0.5-2'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.exclude }}
    - ${{ inputs.extensions }}
    - ${{ inputs.clangFormatVersion }}
